### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by int3hh** [joeblackwaslike/coinaddr#9] opened 2020-11-04 16:13 UTC
```
coinaddr.validate('ltc', b'1111')

TypeError: ("'network' must be <class 'str'> (got None that is a <class 'NoneType'>).",
```

```
print(coinaddr.validate('eth', '111'))

ValidationResult(name='ethereum', ticker='eth', address=b'111', valid=True, network='both')
```

**Comment by bob-jeensk** [comment] 2020-11-09 02:55
i have same issue

**Comment by mumusemu** [comment] 2021-03-02 08:27
i have same issue too

**Comment by xorn99** [comment] 2021-09-14 15:11
Ethereum validator still not working. Validates SHA1 as eth.

**Comment by joeblackwaslike** [comment] 2022-10-17 15:21
looks to be a duplicate of #1, so rolling those two together, please follow that ticket for progress.  Thx for raising the issue.

**Closed as completed by joeblackwaslike** 2022-10-17 15:21 UTC
Labels: bug, duplicate
